# reduce the logging level. set logging level to warn
logging:
  level:
    root: warn
    org:
      hibernate:
        SQL: debug
    org.springframework.security: DEBUG

spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

  datasource:
    url: jdbc:mysql://localhost:3306/new_customers
    username: root
    password: Giridhar@98
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  sql:
    init:
      mode: always
      
  batch:
    job:
      names: myJob
    jdbc:
      initialize-schema: always

server:
  port: 8080

